# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojosecret', '0002_auto_20170502_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
